-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 46251c9523506b68419aefdf5ff6ff2fbc4506a4
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: trailing-whitespace
-   repo: https://bitbucket.org/samwhited/go-pre-commit.git
    sha: cab517ac1132ea76603bd51ba5a95305f81bb2ba
    hooks:
    -   id: gofmt
